services:
  bot:
    environment:
      BOT_TOKEN: ""
      BOT_TOKEN_FILE: /run/secrets/bot_token
    secrets:
      - bot_token

secrets:
  bot_token:
    file: ${BOT_TOKEN_SECRET_FILE:-./secrets/bot_token}
